const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'FriendsBook API',
      version: '1.0.0',
      description: 'FriendsBook API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['../routes/*.js'],
};

module.exports = options;
